# Default value.
field.value.scc_selector_area:
  type: mapping
  label: Default value
  mapping:
    state:
      type: string
      label: State
    county:
      type: string
      label: County
    city:
      type: string
      label: City
